export const SignupStyles = {
  gridContainer: {
    minHeight: "100vh",
    backgroundColor: "#f5f5f5",
  },
  paperContainer: {
    width: "900px",
    height: "500px",
    display: "flex",
    borderRadius: "20px",
    overflow: "hidden",
  },
  leftContainer: {
    flex: 1,
    backgroundColor: "#1B0099",
    color: "white",
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    padding: "40px",
    borderTopRightRadius: "70px",
    borderBottomRightRadius: "70px",
  },
  signInButton: {
    borderColor: "white",
    color: "white",
    mt: 1,
    width: "130px",
    height: "38px",
    fontWeight: "500",
    borderRadius: "8px",
    "&:hover": { backgroundColor: "white", color: "#1B0099" },
  },
  rightContainer: {
    flex: 1,
    backgroundColor: "white",
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    padding: "40px",
  },
  title: {
    color: "#1B0099",
    marginBottom: "30px",
    fontWeight: "bold",
  },
  inputField: {
    marginBottom: "15px",
    width: "320px",
    "& .MuiOutlinedInput-root": {
      backgroundColor: "#f5f5f5",
      borderRadius: "5px",
      height: "35px",
      "&.Mui-focused .MuiSvgIcon-root": { color: "#1B0099" },
    },
  },
  iconStyle: {
    color: "#d9d9d9",
  },
  passwordVisibilityIcon: {
    color: "#1B0099",
  },
  signUpButton: {
    backgroundColor: "#1B0099",
    color: "white",
    borderRadius: "8px",
    marginTop: "10px",
    width: "130px",
    height: "38px",
    fontWeight: "500",
    "&:hover": { backgroundColor: "#0A0066" },
  },
};
