export const loginStyles = {
  gridContainer: {
    minHeight: "100vh",
    backgroundColor: "#f5f5f5",
  },
  paperContainer: {
    width: "900px",
    height: "500px",
    display: "flex",
    borderRadius: "30px",
    overflow: "hidden",
  },
  leftContainer: {
    flex: 1,
    padding: "40px",
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
  },
  title: {
    color: "#1B0099",
    fontWeight: "bold",
    marginBottom: "25px",
  },
  inputField: {
    marginBottom: "15px",
    width: "290px",
    "& .MuiOutlinedInput-root": {
      backgroundColor: "#f5f5f5",
      borderRadius: "5px",
      height: "35px",
      "&.Mui-focused .MuiSvgIcon-root": { color: "#1B0099" },
    },
  },
  button: {
    borderRadius: "8px",
    mt: 1,
    width: "130px",
    height: "38px",
    backgroundColor: "#1B0099",
  },
  rightContainer: {
    flex: 1,
    backgroundColor: "navy",
    color: "white",
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    padding: "40px",
    borderTopLeftRadius: "70px",
    borderBottomLeftRadius: "70px",
  },
  icon: {
    transition: "color 0.3s",
    color: "#d9d9d9",
  },
  lockIcon: {
    color: "#d9d9d9",
    transition: "color 0.3s",
    fontSize: "25px",
  },
  passwordVisibilityIcon: {
    color: "#1B0099",
  },
  signUpButton: {
    borderColor: "white",
    color: "white",
    mt: 1,
    width: "130px",
    height: "38px",
    fontWeight: "500",
    borderRadius: "8px",
    "&:hover": { backgroundColor: "white", color: "#1B0099" },
  },
  forgotPassword: {
    mb: 1,
    cursor: "pointer",
    color: "#1B0099",
    fontSize: "14px",
    transition: "color 0.3s",
    "&:hover": {
      color: "#0E0077",
    },
  },
  googleButtonContainer: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    width: "100%",
  },
  divider: {
    width: "80%",
    mt: 2,
    mb: 3,
    color: "#1B0099",
  },
};
